import {
  IconBarbell,
  IconBath,
  IconBook,
  IconBriefcase,
  IconCar,
  IconCode,
  IconCoffee,
  IconDroplet,
  IconFocus2,
  IconHome,
  IconMail,
  IconMoodSmile,
  IconMoon,
  IconMusic,
  IconPlayerPause,
  IconSchool,
  IconSoup,
  IconSunrise,
  IconToolsKitchen2,
  IconUsers,
  IconWalk,
  IconYoga,
  type Icon,
} from "@tabler/icons-react";

import type { ActivityIcon } from "@/lib/schedule";

export const ACTIVITY_ICONS: Record<ActivityIcon, { icon: Icon; label: string }> = {
  wake: { icon: IconSunrise, label: "Despertar" },
  water: { icon: IconDroplet, label: "Agua" },
  exercise: { icon: IconBarbell, label: "Ejercicio" },
  shower: { icon: IconBath, label: "Baño" },
  breakfast: { icon: IconCoffee, label: "Café o desayuno" },
  focus: { icon: IconFocus2, label: "Enfoque" },
  break: { icon: IconPlayerPause, label: "Pausa" },
  tasks: { icon: IconMail, label: "Correos" },
  lunch: { icon: IconToolsKitchen2, label: "Comida" },
  work: { icon: IconBriefcase, label: "Trabajo" },
  free: { icon: IconMoodSmile, label: "Tiempo libre" },
  dinner: { icon: IconSoup, label: "Cena" },
  read: { icon: IconBook, label: "Lectura" },
  sleep: { icon: IconMoon, label: "Dormir" },
  study: { icon: IconSchool, label: "Estudio" },
  walk: { icon: IconWalk, label: "Caminar" },
  meditate: { icon: IconYoga, label: "Meditar" },
  music: { icon: IconMusic, label: "Música" },
  people: { icon: IconUsers, label: "Personas" },
  commute: { icon: IconCar, label: "Traslado" },
  home: { icon: IconHome, label: "Casa" },
  code: { icon: IconCode, label: "Programar" },
};
